### PR TITLE
Add support for new contracts

### PR DESCRIPTION
**Pull request by patitonar**
Add support for new Native-to-ERC20 contracts on `refactor_v1` branch of `poa-bridge-contracts` repo.

e2e test will fail and Netlify preview won't work correctly until we have a bridge running on Sokol/Kovan working with the new contracts.

### CODE REVIEW

**Comment by igorbarinov** [comment]
Deploy preview for *kind-kilby-95344f* processing.

Built with commit dce4f5c12f645b511574420129c34c239ed2b9c3

https://app.netlify.com/sites/kind-kilby-95344f/deploys/5b61bf15c965923f6d5dfce6

**Comment by akolotov** [comment]
> e2e test will fail and Netlify preview won't work correctly until we have a bridge running on Sokol/Kovan working with the new contracts.

Does it make sense to deploy the corresponding version of contracts and run the corresponding version of bridge-nodejs as part of testing to have tests successfull?

**Comment by patitonar** [comment]
I think those two are good ideas:

- Add contracts repo as submodule. (As we did on bridge-nodejs)
- As part of e2e test deploy contracts and run corresponding version of bridge-nodejs

Should I work on those items as part of this PR?

**Comment by akolotov** [comment]
Thanks for adding the new PR to introduce submodules with contracts!

What the sequence to merge these two PRs is?

**Comment by rstormsf** [comment]
I will deploy new version of contracts on testnet

**Comment by patitonar** [comment]
@rstormsf @akolotov  Please merge #130 first.

Then we need to decide how to solve e2e tests and netlify issues.

Please correct me if I'm wrong or missing something, this is how today scenario is:
- We have old contracts deployed on testnet and bridge instances (rust version) running for those contracts.
- e2e test runs bridge-ui using those old deployed contracts addresses.
- netlify runs PR preview using those same old deployed contracts addresses.

In this PR bridge-ui works with new contract version, so e2e tests fails and netlify preview won't work correctly because they are using old deployed contracts addresses.

A first option is to use same approach as today: 
- Deploy new contract version on testnet.
- Add nodejs bridge instances running for those contracts.
- Update e2e test and netlify to use those new contracts for every PR.

A second option mentioned before for e2e test:
- As part of e2e test (similar to what we do on bridge-nodejs repo) we can deploy contracts, run a bridge-nodejs instance and run test. 

Unfortunately second option will only work for e2e tests scope and won't be available for netlify. I'm not very familiar with netlify features to know if we can provide a similar approach.
If not, unless we have any other option or idea, option one solves both issues.

**Comment by rstormsf** [comment]
if we merge this PR, our production app will be broken because it only works with Rust version events and it will never be changed/switched to nodejs version according to @igorbarinov 
So we cannot merge this PR at all.
We have to come up with new strategy on how we are going to build bridge-ui for nodejs version

**Comment by patitonar** [comment]
This PR is intended to merge into `develop` branch, not `master`. It is safe to merge it into that branch?

**Comment by akolotov** [comment]
Right @patitonar. Since this PR is for `develop` branch I think we could merge it without any risk. Later we could decide what we will do with netlify preview (I would prefer do deploy contracts and a bridge entitiy as part of CD process). Currently, as I can see, it is deployed by netlify without issues so it does not block the merge.

**Comment by akolotov** [comment]
@patitonar do you know why after merging #130 we still have errors related to Travis-CI?

**Comment by patitonar** [comment]
@akolotov Travis-CI is failing because of e2e test. I'm working on fixing that by as part of the e2e adding private nodes, deploying contracts, running a bridge-nodejs instance and running bridge-ui tests over that. After I finish and push the fix, Travis-CI should pass.

**Comment by akolotov** [comment]
@patitonar could you share your plans to finish addressing issues with e2e testing for this PR?

**Comment by patitonar** [comment]
@akolotov I created PR #132 , it has as target the branch from this PR. Travis-CI should pass after those changes. After merging #132 this PR will be completed and ready to merge

**Comment by akolotov** [comment]
I have merged #132. Let's check if the Travis-CI issue has gone.

**Pull request merged**
