### PR TITLE
feat(bridgeUi): Updated the OG descriptions and added the zendesk widget

### PR DESCRIPTION
**Pull request by SiddigZeidan**
Issues: #73, #74 

Need to add different favicon formats

### CODE REVIEW

**Comment by rstormsf** [comment]
Deploy preview for *poabridge* ready!

Built with commit 3c8330b455ddcd96f2a7bbc02838f3e56b69efa8

https://deploy-preview-76--poabridge.netlify.com

**Comment by patitonar** [comment]
@rstormsf @SiddigZeidan Looks good to me.

About #73 , should't the favicon on the browser also need to be updated? 

newfavicon

**Comment by SiddigZeidan** [comment]
@patitonar that has been updated. However, my latest commits are not building, maybe due to e2e scripts not being updated. Will merge latest master into my branch and try again

**Comment by patitonar** [comment]
The favicon seems to be working ok now. You can merge this PR if is ok to you @rstormsf

**Comment by dennis00010011b** [comment]
@SiddigZeidan I still have old favicon
Mac Pro, Chrome Version 66.0.3359.139 (Official Build) (64-bit)

screen shot 2018-05-08 at 09 35 24

**Comment by patitonar** [comment]
@dennis00010011b may be a cache problem? did you try on incognito window?

**Comment by dennis00010011b** [comment]
@patitonar @SiddigZeidan It was problem with cache. After clear the cache and reload system I got new favicon

**Pull request merged**
