### PR TITLE
Fix Event Search

### LINKED ISSUE #62: Events: searching crashes the page
Reproduce:
1. Open URL https://bridge.poa.net/
2. Perform several transaction through the bridge
3. Open tab 'Events'
4. Start to search any existed transaction by Tx Hash

Expected result:
 - search results should be available for short time

Actual result:
 - loader is  displayed for a long time(I've  waited more than 2 minutes)
- page is crashed after reloading

https://drive.google.com/open?id=1ZMCr3L8UezFSnWy5II89lpq59lApjHEY

screen shot 2018-05-02 at 15 24 33

### PR DESCRIPTION
**Pull request by patitonar**
Closes #62

### CODE REVIEW

**Comment by igorbarinov** [comment]
Deploy preview for *kind-kilby-95344f* processing.

Built with commit 668455ddbd1aa13c31fa138c0e32606c5ed66b1b

https://app.netlify.com/sites/kind-kilby-95344f/deploys/5af9cff711b73b3da1a2e2e4

**Comment by dennis00010011b** [comment]
@patitonar 
if search request isn't tx then loader displayed and page frozen unless it will be refreshed 

screen shot 2018-05-14 at 23 34 17

**Comment by dennis00010011b** [comment]
Also , it i impossible to copy-paste Tx 
Tx should be  displayed in full or icon copy/paste should be present near every Tx

**Comment by dennis00010011b** [comment]
Overlapped

screen shot 2018-05-14 at 23 58 04

**Comment by patitonar** [comment]
@dennis00010011b 
- Fixed Overlap on search input
- Added Copy icon next to Tx
- Fixed frozen page on search

**Pull request merged**
