### PR TITLE
Merge the develop-1.x branch to the master-1.x branch

### PR DESCRIPTION
**Pull request by akolotov**
Includes a fix for #164

### CODE REVIEW

**Comment by akolotov** [comment]
@patitonar could you take a look why the build failed?

**Comment by patitonar** [comment]
@akolotov The build is failing because of the e2e tests. The `1.x` version e2e tests uses a deployed rust bridge on `Sokol-Kovan`. It seems that the bridge is not working anymore so every PR to this version will fail. You can check details on the Netlify preview https://5c23bb70fba43700086a71b4--kind-kilby-95344f.netlify.com/

Current version of Bridge UI use Docker to run private parity chains, deploy contracts, run token-bridge and run e2e tests agains that bridge.

**Comment by akolotov** [comment]
@patitonar thanks for info. Will merge the branch then. Could you monitor `http://bridge.poa.network` for few minutes after deployment that will happen after the merge? We need to make sure that it was deployed successfully.

**Comment by patitonar** [comment]
@akolotov Does the deploy to `http://bridge.poa.network` need a manual step? or should it deploy automatically after merging to `master-1.x`?

**Comment by akolotov** [comment]
@patitonar asked Igor to take a look at the netlify configuration.

**Pull request merged**
