### PR TITLE
feat(disclaimerButton): Hide the disabled button

### PR DESCRIPTION
**Pull request by SiddigZeidan**
Personal opinion, I think the "Continue" button should be hidden when the checkbox has not been inputted

@rstormsf 

Issue: #89

### CODE REVIEW

**Comment by igorbarinov** [comment]
Deploy preview for *kind-kilby-95344f* processing.

Built with commit 60a1f466b12e791ce902e4a996ffdc22fcae3627

https://app.netlify.com/sites/kind-kilby-95344f/deploys/5af26256b312746da31145f1

**Comment by rstormsf** [comment]
if @patitonar approves it, then sure

**Comment by patitonar** [comment]
@rstormsf Yes, I think it's a good idea

**Comment by SiddigZeidan** [comment]
@igorbarinov has requested that the checkbox be removed, so Ill update my PR accordingly

**Comment by SiddigZeidan** [comment]
@patitonar , can you check my PR now? I think its good to be merged.

**Comment by patitonar** [comment]
@rstormsf @SiddigZeidan looks good to me!

**Pull request merged**
