### PR TITLE
Add User Wallet and Daily Quota

### PR DESCRIPTION
**Pull request by patitonar**
This PR includes Enhancement 1 and Enhancement 2 from issue #112 
- Show user's wallet address on the Bridge UI
- Real-time view of how many tokens remaining in daily quota

These new features are displayed only on **Desktop**, if we want to display them on mobile we should think about a design to work with mobile menu.

### CODE REVIEW

**Comment by rstormsf** [comment]
@dennis00010011b plz test

**Comment by dennis00010011b** [comment]
@patitonar @rstormsf 
Empty page if to lock the Metamask

https://drive.google.com/file/d/1HJ8m3mxgwbqW-3Y52mjGjP7OAVpqdgIu/view

It is not reproducible with production URL: ```https://bridge.poa.net/```

**Comment by patitonar** [comment]
@dennis00010011b added a fix for the empty page. can you check now?

**Comment by rstormsf** [comment]
@dennis00010011b plz test

**Comment by dennis00010011b** [comment]
@patitonar @rstormsf 
Tested . No issue were found

**Pull request merged**
