### PR TITLE
Add Loading on Account Change

### PR DESCRIPTION
**Pull request by patitonar**
Add the Loading overlay when changing account on Metamask to improve user experience while balances are loaded for the new account

### CODE REVIEW

**Comment by igorbarinov** [comment]
Deploy preview for *kind-kilby-95344f* processing.

Built with commit 1e847a2b7d2ca41ca1990eaf40a6f06b15e75b7d

https://app.netlify.com/sites/kind-kilby-95344f/deploys/5afeef578df894623b47abca

**Comment by rstormsf** [comment]
@dennis00010011b plz test

**Comment by dennis00010011b** [comment]
@patitonar @rstormsf 
Issue: If open info window and change account in metamask then info window shows old account info.
Possible solving: close info window if account is  changed OR renew info window 

screen shot 2018-05-18 at 10 30 30

**Comment by dennis00010011b** [comment]
@patitonar  @rstormsf 
Page unavailable and loader displayed if lock metamask

screen shot 2018-05-18 at 11 02 29

**Comment by patitonar** [comment]
@dennis00010011b added fixes for:
- Update open info window
- Page unavailable and loader displayed if lock metamask

**Comment by dennis00010011b** [comment]
@patitonar @rstormsf 
One more issue: transfer dialog enabled if metamask locked
If metamask is  locked and user tries to send tokens there is should be error message like :"No metamask ....."
 
screen shot 2018-05-18 at 13 52 47

**Comment by rstormsf** [comment]
@dennis00010011b please test

**Comment by dennis00010011b** [comment]
@patitonar @rstormsf 
Tested. No issue were found

**Pull request merged**
