### PR TITLE
Main Page Improvements

### LINKED ISSUE #48: Don't Math.ceil, it's better to Math.floor
image

the  balance  is actually 0.0554321

### LINKED ISSUE #54: UI Arrow shouldn't be displayed if there is unknown network
We need to indicate to the user via alert that he is on unknown to the bridge network and tell him that he needs to specify a particular network (Sokol or Kovan) in order to communicate with the bridge

### LINKED ISSUE #60: New loading screen
https://invis.io/R6HX55MHUW3

### PR DESCRIPTION
**Pull request by patitonar**
This PR includes the following:
- Display balances with Math.floor
- Notification if metamask is not installed or no account selected
- Notification if unknown network selected
- Disclaimer alert
- New loading screen

@rstormsf Please check the workflow and texts from the new loading screen

Regarding the disclaimer alert, it will show up only the first time. After you click on `continue` it will save on localstorage the state to not show it again. I had to do that because when switching the networks on Metamask the page reloads and the alert appeared again. Let me know if that is ok or if I should change the behavior.

Closes #48 , closes #54 , closes #60

### CODE REVIEW

**Comment by rstormsf** [comment]
Deploy preview for *poabridge* ready!

Built with commit 80d278d311534b3864a942f37e7b90dda1beb83d

https://deploy-preview-64--poabridge.netlify.com

**Comment by rstormsf** [comment]
Got it
@patitonar thank you

**Comment by rstormsf** [comment]
@dennis00010011b plz test it out and let us know if you find anything

**Comment by dennis00010011b** [comment]
I've tested: 
 - Display balances with Math.floor
 - Notification if metamask is not installed or no account selected
 - Notification if unknown network selected
 - Disclaimer alert
 - New loading screen
 - https://github.com/poanetwork/bridge-ui/issues/48
 - https://github.com/poanetwork/bridge-ui/issues/54
 - https://github.com/poanetwork/bridge-ui/issues/60

NO issue were found

**Pull request merged**
