### PR TITLE
add AlphaWallet as a supporting wallet for xDAI

### PR DESCRIPTION
**Pull request by James-Sangalli**
For #185

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@patitonar fixed, @akolotov where do you mean? For download links we should have both since then you have support for desktop, iOS and android :)

**Comment by patitonar** [comment]
I think what @akolotov means is that instead of having two buttons for AlphaWallet (one for iOS and one for Android) we should have only one that links to https://alphawallet.com/. If we do that, I think we should update the description (`please install one (AlphaWallet, Metamask or Nifty Wallet)`) to be more clear that Metamask and Nifty Wallet should be installed for browser and AlphaWallet for iOS and Android. What do you think @James-Sangalli ?

**Comment by James-Sangalli** [comment]
@patitonar ok but for the page which says you have no wallet, would you agree that putting the direct download links for an iOS, android and desktop client is best? Would rather the user could get the download promptly rather than searching the website first. 

Agree it would be a good idea to mention in the readme which is desktop and which is mobile :)

**Comment by patitonar** [comment]
@James-Sangalli The current links on Metamask and Nifty wallet buttons doesn't link to their download site, but to a site with instructions on how to download (on different browsers as Chrome and Firefox) and getting started with the wallet. (Actually I just notice that links are broken, but they should be something like https://forum.poa.network/t/nifty-wallet-guide/1789 and https://forum.poa.network/t/wallet-metamask-extension/1819)

I think we should continue with this behavior and so have only one button for `AlphaWallet` that links to the website or an specific page with instructions for the user to download the app on their platform.

That this makes sense?

**Comment by akolotov** [comment]
@James-Sangalli I agree with @patitonar in order to keep better user experience and consistency
1. We provide one link per wallet regardless of the platform. 
2. The link to the instructions how to install and configure the wallet is more preferable since it allows to present how exactly it will address the user's needs.

**Comment by James-Sangalli** [comment]
Ok @akolotov & @patitonar as you wish, I have changed the commit to only use one link which will send the user to a page providing some info and links to download or go to the website. Please merge when you can.

**Comment by James-Sangalli** [comment]
Done.

**Pull request merged**
