### PR TITLE
Update contract submodule

### PR DESCRIPTION
**Pull request by patitonar**
Updated contract submodule to version `2.3.1`

### CODE REVIEW

**Review by akolotov — COMMENTED** [review]
Do you need update the env files to deploy contracts since `2.1.0` and `2.3.1` have different set of fields?

**Comment by akolotov** [comment]
@patitonar e2e testing fails in the TravisCI:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/web3-providers-ws/websocket@git:/github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2" as it does not contain a package.json file.
```

**Comment by patitonar** [comment]
Thanks @akolotov I'm reviewing the issue, it seems that a dependency is having some issues to be fetched. It also affects the PR on the oracle

**Comment by akolotov** [comment]
> Thanks @akolotov I'm reviewing the issue, it seems that a dependency is having some issues to be fetched. It also affects the PR on the oracle

Arsenii Petrovich reported yesterday the same issues in his experiments. He solved it by removing `package.json` in the contracts repository.

**Comment by akolotov** [comment]
The same issue as for https://github.com/poanetwork/bridge-ui/pull/220#issuecomment-495587939 appeared on TravisCI.
Seems that the issue on the contract's side.

**Review by akolotov — APPROVED** [review]

**Pull request merged**
