### PR TITLE
Main page fixes

### LINKED ISSUE #44: Arrow doesn't change when submit tx and switching network

### PR DESCRIPTION
**Pull request by patitonar**
Closes #44 , #43 , #42 , #49 , #52 , #51 , #45 , #58

### CODE REVIEW

**Comment by rstormsf** [comment]
Deploy preview for *poabridge* ready!

Built with commit ba48675e11535943a5f973797116be7b618227ac

https://deploy-preview-59--poabridge.netlify.com

**Comment by rstormsf** [comment]
@patitonar I can still see my  old balance if I switch metamask account

**Comment by patitonar** [comment]
@rstormsf I checked and while the home side the balance is checked every 5 seconds, on the foreign side it is being checked every 15 seconds. May be we should check every 5 seconds too.

**Comment by dennis00010011b** [comment]
@patitonar 
https://github.com/poanetwork/bridge-ui/issues/45 . still there

**Comment by dennis00010011b** [comment]
https://github.com/poanetwork/bridge-ui/issues/49
Fixed in portrait mode
Page non-scrollable and non-zoomed in landscape mode
Tested with Samsung Galaxy J7, Android 7.0, Chrome

**Comment by rstormsf** [comment]
@patitonar yeah  maybe we should do it every 5 sec too

**Comment by patitonar** [comment]
@rstormsf Updated foreign to every 5 seconds.

@dennis00010011b can you check now on #45 and #49 ?

**Comment by rstormsf** [comment]
same link?
https://deploy-preview-59--poabridge.netlify.com
@patitonar

**Comment by patitonar** [comment]
@rstormsf yes, it seems to be the same link. Clear the cache just in case

**Comment by rstormsf** [comment]
image

looks good. Now I will ask the designer to fix some of the UX problems

**Comment by rstormsf** [comment]
looks good to me. merging

**Pull request merged**
